#      _   _           _     _____  _             _                    #
#     | \ | |         | |   |  __ \| |           (_)                   #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___          #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|         #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \         #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/         #
#                                           __/ |                      #
#                                          |___/                       #
#                          Servidor de Suporte                         #
#                         discord.gg/JtTN7E6A2q                        #

######### ATENÇÃO #########
# Caso queira executar o sorteio em x horario e dia
# utilize o nosso plugin NextTasks, ele automatiza vários comandos
# coloque a hora e o dia que você quiser, e ponha o comando /sortear
# logo, ele irá executar o sorteio (caso tenha os jogadores mínimos)
# para forçar o início de um sorteio sem os jogadores mínimos,
# utilize '/sortear force' assim irá forçar o início de um sorteio

configuration:
  # Jogadores online mínimos para iniciar um sorteio
  minPlayers: 30
  # Quantas vezes irá enviar o título de sorteando
  # antes de selecionar um vencedor
  # Atenção: O title é enviado a cada 0.5 segundos
  # caso coloque 20 executes, irá demorar 10 segundos para sortear
  executes: 20
  # Som que irá tocar quando iniciar o sorteio
  # Cheque a lista de sons para sua versão do servidor
  # Versão 1.8.8 https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  # Versão 1.12.2 https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
  # Versão 1.16.4 https://helpch.at/docs/1.16.4/org/bukkit/Sound.html
  sound: NOTE_PLING
  # Som que irá tocar quando sortear um vencedor
  # Cheque a lista de sons para sua versão do servidor
  # Versão 1.8.8 https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  # Versão 1.12.2 https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
  # Versão 1.16.4 https://helpch.at/docs/1.16.4/org/bukkit/Sound.html
  winSound: ENDERDRAGON_GROWL

messages:
  sorting:
    title: '&6&knextoprugins<nl>&fProcurando um sortudo para receber um &eprêmio'
    # Tempo em ticks
    # 1 segundo possui 20 ticks
    time: 5
  sorted:
    title: '&6Temos um vencedor!<nl>&e@player &frecebeu @prize&e!'
    # Tempo em ticks
    # 1 segundo possui 20 ticks
    time: 200
  winMessage:
    - ''
    - "&6&LSORTEIO &fVocê &evenceu &fum sorteio e recebeu &e'&f@prize&e'"
    - ''